
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: tux123
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true

info:
  app:
    name: "loans"
    description: "Demo Bank Loans Microservice"
    version: "1.0.0"

server:
  port: 8082