server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: tux123
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  #  profiles:
#    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active:
#      - "qa"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

#build:
#  version: "1.0-SNAPSHOT"
#
#accounts:
#  message: "Welcome to demo of SimpleBank Accounts microservice for Development environment"
#  contactDetails:
#    name: "Yauri Attamimi"
#    email: "yauritux@gmail.com"
#  onCallSupport:
#    - +81 777 55123577
#    - +62 21 77348484